### ISSUE TITLE
2.1 incompatibility

### ISSUE THREAD

**Issue by marcoow** [Vestorly/torii#225]
I'm getting the error

```
TypeError: handler.run is not a function
```

when running the latest beta release 0.6.0-beta.4 with Ember 2.1. The error seems to be caused by [this line](https://github.com/Vestorly/torii/blob/master/lib/torii/initializers/initialize-torii-callback.js#L8) - not sure whether it's actually related to 2.1 but it seems to work with 2.0.

**Comment by mixonic** [comment]
closed by https://github.com/Vestorly/torii/pull/232 + https://github.com/Vestorly/torii/commit/1fec0d2472a7933a888785c7138fa647b5c2ec92. Published as 0.6.0-beta.5. Thanks Marco! Let me know if the issues persists.

**Comment by marcoow** [comment]
I'm seeing a different error now:

```
TypeError: application.has is not a function
```

That seems to be caused by [this line](https://github.com/Vestorly/torii/blob/c3db4b0b27127a4265aee75ed50384a95fb19b53/lib/torii/bootstrap/torii.js#L37). I guess the correct method in 2.1 is `hasRegistration`?

Do you want me to create a new ticket  or will you reopen this one?

**Comment by bmeyers22** [comment]
@mixonic Made a pull request that should fix this #234
