### ISSUE TITLE
Incompatible with Ember Engines

### ISSUE THREAD

**Issue by ChavaSobreyra** [Vestorly/torii#334]
Tried to use with ember-engines today. I'm getting an error from the (initializers/initialize-torii-callback.js)[https://github.com/Vestorly/torii/blob/master/app/initializers/initialize-torii-callback.js].

`TypeError: application.deferReadiness is not a function`

and elsewhere: 
'TypeError: application.deferReadiness is not a function'

I'm guessing from (instance-initializers/setup-routes.js)[https://github.com/Vestorly/torii/blob/master/app/instance-initializers/setup-routes.js]

**Comment by crodriguez1a** [comment]
@ChavaSobreyra I was able to get the latest version working with engines 0.5.4. I went with a nested approach like this:

```es6
this.authenticatedRoute('secure', function() {
  this.mount('secure-engine', { as: 'foo'});
});
```

**Comment by danielthall** [comment]
@ChavaSobreyra Did you ever work around this? I'm having the same issue.

**Comment by knownasilya** [comment]
Have also encountered this.
